### PR TITLE
disable ifd by default

### PR DESCRIPTION
**Pull request by figsoda**
also added `--allow-ifd`/`--allow-import-from-derivation` to renable ifd

### CODE REVIEW

**Comment by figsoda** [comment]
tests got rate limited :thinking:

**Comment by Mic92** [comment]
Do use the github token from the github actions runner there?

This is what nixpkgs-review would use:

```
  token = os.environ.get("GITHUB_OAUTH_TOKEN", os.environ.get("GITHUB_TOKEN"))
```

**Comment by Mic92** [comment]
github actions exposes this via `${{ secrets.GITHUB_TOKEN }}`

**Comment by Mic92** [comment]
addressed in https://github.com/Mic92/nixpkgs-review/pull/289

**Comment by Mic92** [comment]
bors merge

**Comment by Mic92** [comment]
bors merge

**Pull request merged**
