### PR TITLE
Use buildEnv to support longer paths

### PR DESCRIPTION
**Pull request by SuperSandro2000**

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
@Mic92 tested it a bit and should be mostly functional

**Comment by SuperSandro2000** [comment]
@Mic92 I am not sure if the bug I observed was there before I've added buildEnv but when you execute a command that does not exist in a review shell and then you exit it with ``exit`` the review process would be stopped if you reviewed multiple PRs.

**Comment by SuperSandro2000** [comment]
I think we need to add `appimage-run-tests` to the blacklist of packages:

```
this derivation will be built:
  /nix/store/sjv7laa18zh7hmi5kpr5r4ncnbxfhghd-env.drv
building '/nix/store/sjv7laa18zh7hmi5kpr5r4ncnbxfhghd-env.drv'...
The store path /nix/store/r9m1m6sj77qjhvjh5zlcgqwfaipsy8gs-appimage-run-tests is a file and can't be merged into an environment using pkgs.buildEnv! at /nix/store/q9d93xv7n6gnnsah07smswwav50m0kis-builder.pl line 109.
The store path /nix/store/r9m1m6sj77qjhvjh5zlcgqwfaipsy8gs-appimage-run-tests is a file and can't be merged into an environment using pkgs.buildEnv! at /nix/store/q9d93xv7n6gnnsah07smswwav50m0kis-builder.pl line 109.
builder for '/nix/store/sjv7laa18zh7hmi5kpr5r4ncnbxfhghd-env.drv' failed with exit code 2
```

**Comment by Mic92** [comment]
> I think we need to add `appimage-run-tests` to the blacklist of packages:
> 
> ```
> this derivation will be built:
>   /nix/store/sjv7laa18zh7hmi5kpr5r4ncnbxfhghd-env.drv
> building '/nix/store/sjv7laa18zh7hmi5kpr5r4ncnbxfhghd-env.drv'...
> The store path /nix/store/r9m1m6sj77qjhvjh5zlcgqwfaipsy8gs-appimage-run-tests is a file and can't be merged into an environment using pkgs.buildEnv! at /nix/store/q9d93xv7n6gnnsah07smswwav50m0kis-builder.pl line 109.
> The store path /nix/store/r9m1m6sj77qjhvjh5zlcgqwfaipsy8gs-appimage-run-tests is a file and can't be merged into an environment using pkgs.buildEnv! at /nix/store/q9d93xv7n6gnnsah07smswwav50m0kis-builder.pl line 109.
> builder for '/nix/store/sjv7laa18zh7hmi5kpr5r4ncnbxfhghd-env.drv' failed with exit code 2
> ```

Ok. we can have a chat this evening.

**Comment by SuperSandro2000** [comment]
We both forgot it. So how do we want to solve this?

**Pull request merged**
