### PR TITLE
Eval fixes

### PR DESCRIPTION
**Pull request by jonringer**
Keep running into these issues when reviewing staging PRs

### CODE REVIEW

**Comment by jonringer** [comment]
Testing this on some PRs. Takes a while for `nix-env -qa` to run.

**Comment by jonringer** [comment]
cc @Mic92 looks ready to go, was able to eval https://github.com/NixOS/nixpkgs/pull/142593 by adding `--disable-aliases`

**Review by SuperSandro2000 — APPROVED** [review]
ofborg sometimes puts some aliases in the eval results. I am not sure why but it seems to always be gnome.*

**Comment by jonringer** [comment]
> ofborg sometimes puts some aliases in the eval results. I am not sure why but it seems to always be gnome.*

unless you're reviewing a PR made against master, it will force the eval to include aliases

```
 --disable-aliases     Disable aliases while evaluating locally. They are automatically disabled when reviewing
                        NixOS/nixpkgs PRs against master.
```

**Comment by SuperSandro2000** [comment]
Yeah, we put that in because PRs from stable could still contain aliases and it is not easy to remove them there.

Maybe those lines need to be updated https://github.com/Mic92/nixpkgs-review/blob/ab4a35df2c885f29e336aa3c3e30734283989b80/nixpkgs_review/cli/pr.py#L41-L44

The intention was, that only aliases are forbidden when reviewing PRs merged against master.

**Comment by jonringer** [comment]
> Yeah, we put that in because PRs from stable could still contain aliases and it is not easy to remove them there.

There's an ofborg check to prevent that situation. There should be no alias usage within nixpkgs.

example PR: https://github.com/NixOS/nixpkgs/pull/156318

```
 ofborg-eval-package-list-no-aliases — nix-env -qa --json --file . --arg config { allowAliases = false; }
```

**Comment by jonringer** [comment]
> The intention was, that only aliases are forbidden when reviewing PRs merged against master.

#255

**Comment by SuperSandro2000** [comment]
I merged #255 and pushed 1ad19620ef898df35f80b9ee03d18bf80dfbe003 to master.

**Pull request closed without merging**
