### PR TITLE
add missing args to local reviews

### PR DESCRIPTION
**Pull request by Mic92**
Context: https://github.com/Mic92/nixpkgs-review/issues/363
Haven't really test it yet. @Atemu can you?

```
nix shell github:Mic92/nixpkgs-review/missing-args
```

### CODE REVIEW

**Comment by Atemu** [comment]
Running my minimal repro on it now

**Review by Atemu — APPROVED** [review]
```
1 package updated:
hello

Nothing to be built.
```

**Comment by Atemu** [comment]
Also just worked on the huge staging eval, fixes #363.

**Comment by Mic92** [comment]
@mergify queue

**Pull request merged**
